# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed36e2b9833e87a6983b7cbf2047cb670cddd8f62c5734541e6ff5b862e2b2941c112172e3661fcb649f93c2db5b580fd5666857b169ac795b8776f4652bea52

test:
  secret_key_base: df15d6808a2b3a44b80ed07123710af742c88c5998edf14a464efc3d3bb45c5caeef43a588ca9e93a510bc235d9d011aaec8f276d50403b5af446b6d228b6c9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
